/**
 * BackEndTwo | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Claim } from './claim';


export interface UserInfo { 
    userName: string;
    claims: Array<Claim>;
}

