/**
 * BackEndForFrontend | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Claim { 
    type: string | null;
    value: string | null;
    source: string | null;
}

