/**
 * BackEndTwo | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { UserInfo } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EchoUserInfoServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/EchoUserInfo
     */
    apiEchoUserInfoGet(extraHttpRequestParams?: any): Observable<UserInfo>;

}
