/* tslint:disable */
/* eslint-disable */
/**
 * BackEndForFrontend | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Claim,
  UserInfo,
} from '../models/index';
import {
    ClaimFromJSON,
    ClaimToJSON,
    UserInfoFromJSON,
    UserInfoToJSON,
} from '../models/index';

/**
 * BackEndForFrontendApi - interface
 * 
 * @export
 * @interface BackEndForFrontendApiInterface
 */
export interface BackEndForFrontendApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackEndForFrontendApiInterface
     */
    userBackendoneClaimsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Claim>>>;

    /**
     */
    userBackendoneClaimsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Claim>>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BackEndForFrontendApiInterface
     */
    userInfoGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserInfo>>;

    /**
     */
    userInfoGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserInfo>;

}

/**
 * 
 */
export class BackEndForFrontendApi extends runtime.BaseAPI implements BackEndForFrontendApiInterface {

    /**
     */
    async userBackendoneClaimsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Claim>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/user/backendone/claims`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ClaimFromJSON));
    }

    /**
     */
    async userBackendoneClaimsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Claim>> {
        const response = await this.userBackendoneClaimsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async userInfoGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserInfo>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/user/info`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserInfoFromJSON(jsonValue));
    }

    /**
     */
    async userInfoGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserInfo> {
        const response = await this.userInfoGetRaw(initOverrides);
        return await response.value();
    }

}
