/**
 * BackEndOne | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Claim } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface EchoUserClaimsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/EchoUserClaims
     */
    apiEchoUserClaimsGet(extraHttpRequestParams?: any): Observable<Array<Claim>>;

}
